# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "applink member update",
    is_experimental=True,
)
class Update(AAZCommand):
    """Update a AppLinkMember
    """

    _aaz_info = {
        "version": "2025-08-01-preview",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.applink/applinks/{}/applinkmembers/{}", "2025-08-01-preview"],
        ]
    }

    AZ_SUPPORT_NO_WAIT = True

    AZ_SUPPORT_GENERIC_UPDATE = True

    def _handler(self, command_args):
        super()._handler(command_args)
        return self.build_lro_poller(self._execute_operations, self._output)

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.member_name = AAZStrArg(
            options=["--member-name"],
            help="The name of the AppLinkMember",
            required=True,
            id_part="child_name_1",
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z0-9-]{3,24}$",
            ),
        )
        _args_schema.applink_name = AAZStrArg(
            options=["--applink-name"],
            help="The name of the AppLink",
            required=True,
            id_part="name",
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z0-9-]{3,24}$",
            ),
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            help="Name of resource group",
            required=True,
        )

        # define Arg Group "FullyManagedUpgradeProfile"

        _args_schema = cls._args_schema
        _args_schema.release_channel = AAZStrArg(
            options=["--release-channel"],
            arg_group="FullyManagedUpgradeProfile",
            help="Release channel",
            enum={"Rapid": "Rapid", "Stable": "Stable"},
        )

        # define Arg Group "Properties"

        # define Arg Group "Resource"

        _args_schema = cls._args_schema
        _args_schema.tags = AAZDictArg(
            options=["--tags"],
            arg_group="Resource",
            help="Resource tags.",
            nullable=True,
        )

        tags = cls._args_schema.tags
        tags.Element = AAZStrArg(
            nullable=True,
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        self.AppLinkMembersGet(ctx=self.ctx)()
        self.pre_instance_update(self.ctx.vars.instance)
        self.InstanceUpdateByJson(ctx=self.ctx)()
        self.InstanceUpdateByGeneric(ctx=self.ctx)()
        self.post_instance_update(self.ctx.vars.instance)
        yield self.AppLinkMembersCreateOrReplace(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    @register_callback
    def pre_instance_update(self, instance):
        pass

    @register_callback
    def post_instance_update(self, instance):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class AppLinkMembersGet(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AppLink/appLinks/{appLinkName}/appLinkMembers/{appLinkMemberName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "appLinkMemberName", self.ctx.args.member_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "appLinkName", self.ctx.args.applink_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-08-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()
            _UpdateHelper._build_schema_app_link_member_read(cls._schema_on_200)

            return cls._schema_on_200

    class AppLinkMembersCreateOrReplace(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [202]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )
            if session.http_response.status_code in [200, 201]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AppLink/appLinks/{appLinkName}/appLinkMembers/{appLinkMemberName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PUT"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "appLinkMemberName", self.ctx.args.member_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "appLinkName", self.ctx.args.applink_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-08-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=self.ctx.vars.instance,
            )

            return self.serialize_content(_content_value)

        def on_200_201(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200_201
            )

        _schema_on_200_201 = None

        @classmethod
        def _build_schema_on_200_201(cls):
            if cls._schema_on_200_201 is not None:
                return cls._schema_on_200_201

            cls._schema_on_200_201 = AAZObjectType()
            _UpdateHelper._build_schema_app_link_member_read(cls._schema_on_200_201)

            return cls._schema_on_200_201

    class InstanceUpdateByJson(AAZJsonInstanceUpdateOperation):

        def __call__(self, *args, **kwargs):
            self._update_instance(self.ctx.vars.instance)

        def _update_instance(self, instance):
            _instance_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=instance,
                typ=AAZObjectType
            )
            _builder.set_prop("properties", AAZObjectType)
            _builder.set_prop("tags", AAZDictType, ".tags")

            properties = _builder.get(".properties")
            if properties is not None:
                properties.set_prop("fullyManagedUpgradeProfile", AAZObjectType)

            fully_managed_upgrade_profile = _builder.get(".properties.fullyManagedUpgradeProfile")
            if fully_managed_upgrade_profile is not None:
                fully_managed_upgrade_profile.set_prop("releaseChannel", AAZStrType, ".release_channel", typ_kwargs={"flags": {"required": True}})

            tags = _builder.get(".tags")
            if tags is not None:
                tags.set_elements(AAZStrType, ".")

            return _instance_value

    class InstanceUpdateByGeneric(AAZGenericInstanceUpdateOperation):

        def __call__(self, *args, **kwargs):
            self._update_instance_by_generic(
                self.ctx.vars.instance,
                self.ctx.generic_update_args
            )


class _UpdateHelper:
    """Helper class for Update"""

    _schema_app_link_member_read = None

    @classmethod
    def _build_schema_app_link_member_read(cls, _schema):
        if cls._schema_app_link_member_read is not None:
            _schema.id = cls._schema_app_link_member_read.id
            _schema.location = cls._schema_app_link_member_read.location
            _schema.name = cls._schema_app_link_member_read.name
            _schema.properties = cls._schema_app_link_member_read.properties
            _schema.system_data = cls._schema_app_link_member_read.system_data
            _schema.tags = cls._schema_app_link_member_read.tags
            _schema.type = cls._schema_app_link_member_read.type
            return

        cls._schema_app_link_member_read = _schema_app_link_member_read = AAZObjectType()

        app_link_member_read = _schema_app_link_member_read
        app_link_member_read.id = AAZStrType(
            flags={"read_only": True},
        )
        app_link_member_read.location = AAZStrType(
            flags={"required": True},
        )
        app_link_member_read.name = AAZStrType(
            flags={"read_only": True},
        )
        app_link_member_read.properties = AAZObjectType()
        app_link_member_read.system_data = AAZObjectType(
            serialized_name="systemData",
            flags={"read_only": True},
        )
        app_link_member_read.tags = AAZDictType()
        app_link_member_read.type = AAZStrType(
            flags={"read_only": True},
        )

        properties = _schema_app_link_member_read.properties
        properties.cluster_type = AAZStrType(
            serialized_name="clusterType",
        )
        properties.fully_managed_upgrade_profile = AAZObjectType(
            serialized_name="fullyManagedUpgradeProfile",
        )
        properties.metadata = AAZObjectType(
            flags={"required": True},
        )
        properties.mode = AAZStrType()
        properties.observability_settings = AAZObjectType(
            serialized_name="observabilitySettings",
        )
        properties.provisioning_state = AAZStrType(
            serialized_name="provisioningState",
            flags={"read_only": True},
        )
        properties.self_managed_upgrade_profile = AAZObjectType(
            serialized_name="selfManagedUpgradeProfile",
        )

        fully_managed_upgrade_profile = _schema_app_link_member_read.properties.fully_managed_upgrade_profile
        fully_managed_upgrade_profile.release_channel = AAZStrType(
            serialized_name="releaseChannel",
            flags={"required": True},
        )

        metadata = _schema_app_link_member_read.properties.metadata
        metadata.resource_id = AAZStrType(
            serialized_name="resourceId",
            flags={"required": True},
        )

        observability_settings = _schema_app_link_member_read.properties.observability_settings
        observability_settings.logs = AAZObjectType()
        observability_settings.managed_identity = AAZStrType(
            serialized_name="managedIdentity",
        )
        observability_settings.metrics = AAZObjectType()
        observability_settings.traces = AAZObjectType()

        logs = _schema_app_link_member_read.properties.observability_settings.logs
        logs.state = AAZStrType(
            flags={"required": True},
        )

        metrics = _schema_app_link_member_read.properties.observability_settings.metrics
        metrics.state = AAZStrType(
            flags={"required": True},
        )

        traces = _schema_app_link_member_read.properties.observability_settings.traces
        traces.state = AAZStrType(
            flags={"required": True},
        )

        self_managed_upgrade_profile = _schema_app_link_member_read.properties.self_managed_upgrade_profile
        self_managed_upgrade_profile.version = AAZStrType(
            flags={"required": True},
        )

        system_data = _schema_app_link_member_read.system_data
        system_data.created_at = AAZStrType(
            serialized_name="createdAt",
        )
        system_data.created_by = AAZStrType(
            serialized_name="createdBy",
        )
        system_data.created_by_type = AAZStrType(
            serialized_name="createdByType",
        )
        system_data.last_modified_at = AAZStrType(
            serialized_name="lastModifiedAt",
        )
        system_data.last_modified_by = AAZStrType(
            serialized_name="lastModifiedBy",
        )
        system_data.last_modified_by_type = AAZStrType(
            serialized_name="lastModifiedByType",
        )

        tags = _schema_app_link_member_read.tags
        tags.Element = AAZStrType()

        _schema.id = cls._schema_app_link_member_read.id
        _schema.location = cls._schema_app_link_member_read.location
        _schema.name = cls._schema_app_link_member_read.name
        _schema.properties = cls._schema_app_link_member_read.properties
        _schema.system_data = cls._schema_app_link_member_read.system_data
        _schema.tags = cls._schema_app_link_member_read.tags
        _schema.type = cls._schema_app_link_member_read.type


__all__ = ["Update"]
