# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

from azure.cli.testsdk import ScenarioTest, ResourceGroupPreparer
from .custom_preparers import AKSCustomResourceGroupPreparer

class BaseScenario(ScenarioTest):
    def create_applink(self):
        """Creates an applink, and returns its name. Additionally updates the kwargs to include the name"""
        applink_name = self.create_random_name(prefix="cliapplink", length=20)
        self.kwargs.update({
            "applink_name": applink_name
        })
        self.cmd('applink create --resource-group {rg} --applink-name {applink_name} --location westus2', checks=[
            self.check("name", applink_name)
        ])
        return applink_name

    def create_aks_cluster(self):
        """Creates an AKS cluster, and returns its name. Additionally updates the kwargs to include the name and the resource id"""
        aks_cluster_name = self.create_random_name(prefix="cliaks", length=15)

        self.kwargs.update({
            "aks_name": aks_cluster_name,
        })
        cluster = self.cmd('aks create \
                 --resource-group {rg} --name {aks_name} \
                 --enable-oidc-issuer --enable-workload-identity --os-sku AzureLinux',
                 checks=[
                     self.check("provisioningState", "Succeeded")
                 ]).get_output_in_json()
        aks_resource_id = cluster['id']
        self.kwargs.update({
            "aks_resource_id": aks_resource_id
        })
        return aks_cluster_name, aks_resource_id

    def create_applink_member_fully_managed(self, create_applink=True, create_aks_cluster=True):
        if create_applink:
            self.create_applink()
        if create_aks_cluster:
            self.create_aks_cluster()

        member_name = self.create_random_name(prefix="cliapplinkmember", length=24)
        self.kwargs.update({
            "member_name": member_name
        })
        join_cmd = (
            "applink member join --resource-group {rg} --applink-name {applink_name} "
            "--member-name {member_name} --cluster-type AKS --member-resource-id {aks_resource_id} "
            "--upgrade-mode FullyManaged --release-channel Stable"
        )
        self.cmd(join_cmd, checks=[
            self.check('name', member_name),
            self.check('properties.fullyManagedUpgradeProfile.releaseChannel', "Stable"),
            self.check('properties.mode', "FullyManaged"),
        ])
        return member_name



class ApplinkPreviewScenario(BaseScenario):
    @ResourceGroupPreparer()
    def test_applink_list_no_resources(self, resource_group):
        # Test listing when no resources exist (would return empty list)
        # This test would only run when creating recordings with real authentication
        self.cmd('applink list --resource-group {rg}', checks=[
            self.check('length(@)', 0)  # Expect empty array
        ])

    @ResourceGroupPreparer()
    def test_applink_create(self, resource_group):
        # Test listing when no resources exist (would return empty list)
        # This test would only run when creating recordings with real authentication
        applink_name = self.create_applink()
        self.cmd('applink show --resource-group {rg} --name {applink_name}', checks=[
            self.check("name", applink_name),
            self.check('properties.provisioningState', 'Succeeded')
        ])

    @ResourceGroupPreparer()
    def test_applink_delete(self, resource_group):
        self.create_applink()
        self.cmd('applink delete --resource-group {rg} --name {applink_name} --yes')


class ApplinkMemberPreviewScenario(BaseScenario):
    def __init__(self, *args, **kwargs):
        super(ApplinkMemberPreviewScenario, self).__init__(*args, **kwargs)

    @AKSCustomResourceGroupPreparer()
    def test_applink_member_join_fully_managed(self, resource_group):
        member_name = self.create_applink_member_fully_managed()

        get_cmd = "applink member show --resource-group {rg} --applink-name {applink_name} --member-name {member_name}"
        self.cmd(get_cmd, checks=[
            self.check('name', member_name),
            self.check('properties.fullyManagedUpgradeProfile.releaseChannel', "Stable"),
            self.check('properties.mode', "FullyManaged"),
        ])

        update_cmd = (
            "applink member update --resource-group {rg} --applink-name {applink_name} "
            "--member-name {member_name} --release-channel Rapid"
        )
        self.cmd(update_cmd, checks=[
            self.check('name', member_name),
            self.check('properties.fullyManagedUpgradeProfile.releaseChannel', "Rapid"),
            self.check('properties.mode', "FullyManaged"),
        ])
