# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

from azure.cli.testsdk import *


class ApplinkPreviewScenario(ScenarioTest):
    @ResourceGroupPreparer()
    def test_applink_list_no_resources(self, resource_group):
        # Test listing when no resources exist (would return empty list)
        # This test would only run when creating recordings with real authentication
        self.cmd('applink list --resource-group {rg}', checks=[
            self.check('length(@)', 0)  # Expect empty array
        ])

