# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command_group(
    "applink member upgrade-history",
    is_experimental=True,
)
class __CMDGroup(AAZCommandGroup):
    """Get all version changes of an applink member
    """
    pass


__all__ = ["__CMDGroup"]
